import Head from 'next/head'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Spotify-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>This is a DOPE spotify build...</h1>

      <main>
        {/* Sidebar */}
        {/* Center */}
      </main>

      <div>
        {/* player */}
      </div>
    </div>
  )
}
